theme = "solarized_light"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
backspace = ["delete_char_backward"]
del = ["delete_char_forward"]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_line_start"]

#[keys.normal.ä]
#d = ["goto_next_diag"]
#D = ["goto_last_diag"]
#f = ["goto_next_function"]
#t = ["goto_next_class"]
#a = ["goto_next_parameter"]
#c = ["goto_next_comment"]
#T = ["goto_next_test"]
#p = ["goto_next_paragraph"]
#g = ["goto_next_change"]
#G = ["goto_last_change"]
#space = ["add_newline_above"]

#[keys.normal.ü]
#d = ["goto_prev_diag"]
#D = ["goto_first_diag"]
#f = ["goto_prev_function"]
#t = ["goto_prev_class"]
#a = ["goto_prev_parameter"]
#c = ["goto_prev_comment"]
#T = ["goto_prev_test"]
#p = ["goto_prev_paragraph"]
#g = ["goto_prev_change"]
#G = ["goto_first_change"]
#space = ["add_newline_below"]
